return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "awk",
      "bash",
      "c",
      "cpp",
      "cmake",
      "comment",
      "doxygen",
      "diff",
      "html",
      "css",
      "scss",
      "sql",
      "javascript",
      "jsdoc",
      "json",
      "jsonc",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
      "regex",
    },
    -- Autoinstall languages that are not installed.
    auto_install = true,
    autotag = {
      enable = true,
      enable_rename = true,
      enable_close = true,
      enable_close_on_slash = true,
      filetypes = { "html", "xml" },
    },
  },
}
